### ISSUE TITLE
Add more customizability (discussion)

### ISSUE THREAD

**Issue by appreciated** [tsuoanttila/sidemenu-addon#11]
The behavior of the sidemenu can currently be changed by Code only very rudimentary. 
A improvement would be to allow the user to add custom components to the menu.
Currently changing the look and the behavior requires knowledge of the responsive features of Vaadin, and many CSS modifications.
Maybe a few CSS Examples could be added to the Component to make it easier for the programmer. 

A few ideas/examples:
- Add a sticky Header and a sticky Footer to the sidemenu (Most of the behavior of the added Components needs to should handled by the programmer)
- Show a way how to hide the Logo Wrapper when Menu is folded out for the desktop (and replace it by a custom header)
- Show how the User Menu can be hidden when the Menu is folded out for the desktop and use other components to replace them
- Show how more actions can be added to the User Menu
- Show how custom Components to be added to the Header and Footer in a way which allows that the Components won't be shown in the "mobile" version
- Show how the Menu behavior to be changed that there is no full expanded version for the desktop (f.E. https://dribbble.com/shots/3536328-Click-To-Check-Friend-s-Profile)

**Comment by tsuoanttila** [comment]
The original use-case I had in mind when I did this, was to reduce the amount of understanding needed from a programmer to be able to build this. It took me a whole day to figure out which style names I need to use for which part of the menu to make it work and behave as it's supposed to. I've tried to provide a Java API for doing the things you'd normally do with it.

Such examples would be awesome, even better if those could be made as custom styles and applied into the built in css, and usable through predefined class names. I'll try to talk to some more CSS oriented people to see if I can get some help achieving at least some of the ideas presented here, but I don't know how soon that is.
