### ISSUE TITLE
No mobile view for iPhone 6s

### ISSUE THREAD

**Issue by marcpopp** [tsuoanttila/sidemenu-addon#3]
The responsiveness of the sidemenu layout works great on desktops, but on iPhone or when using the developer tools in chrome smaller mobile views are not displayed as mobile but as normal desktop views with a viewport width of 960px.

I have the problem in my app and in the online demo app. here is screenshot of an iPhone 6s:
![image](https://cloud.githubusercontent.com/assets/5837636/19905706/3a123dca-a078-11e6-8ab7-1a94446591d1.png)

**Comment by marcpopp** [comment]
I could fix that issue by adding the annotation line 
`@Viewport("user-scalable=no,initial-scale=1.0")`
to my UI class.

**Comment by tsuoanttila** [comment]
Looks like the `@Viewport` annotation did not work the way I thought it would. But yes, that's the annotation I should have in the UI as well. Need to test and fix it this weekend.
