### ISSUE TITLE
how to set default opened page?

### ISSUE THREAD

**Issue by zho** [tsuoanttila/sidemenu-addon#4]
how to set default opened page?

i create something like this, but the dashboard not opened

        sideMenu.addMenuItem("Dashboard", () -> {
            VerticalLayout content = new VerticalLayout();
            content.addComponent(new Label("Dashboard"));
            sideMenu.setContent(content);
        });

        sideMenu.addMenuItem("Logout", FontAwesome.ARROW_CIRCLE_O_LEFT, () -> {
            getPage().setLocation("/logout");
        });

        setContent(sideMenu);

is there any special command to set the default opened page?

**Comment by tsuoanttila** [comment]
I'll need to an API to open a specific page, so you can handle the navigation from the server-side code as well.
