### ISSUE TITLE
Can't set logo with SideMenu::setMenuCaption

### ISSUE THREAD

**Issue by capybaracreations** [tsuoanttila/sidemenu-addon#5]
Currently when importing the demo project or adding my own dependency:
```
<dependency>
    <groupId>org.vaadin.teemusa</groupId>
    <artifactId>sidemenu</artifactId>
    <version>1.0</version>
</dependency>
```
There's error with this line:
`    sideMenu.setMenuCaption(menuCaption, logo);`

From the sources I can see that this method does not support second parameter.

Is there any new version on Maven available, which allows it?
I can see that here on GitHub it is updated but I dont see any way of including it.

**Comment by tsuoanttila** [comment]
There is such API at least in the project itself. Might be I have forgotten to release the new version of this after the change was made.

Building a new version to make sure this will be available for users.
