### ISSUE TITLE
incompatible with 8.0.5

### ISSUE THREAD

**Issue by dcosio-ct** [tsuoanttila/sidemenu-addon#6]
`import com.vaadin.shared.ui.label.ContentMode;` in sidemenu class fails for vaadin 8.
package import needs to change to `import com.vaadin.shared.ui.ContentMode;`

**Comment by dcosio-ct** [comment]
I fixed this. I submitted a pull request

**Comment by tsuoanttila** [comment]
Closed with #7 

Thank you very much @dcosio-ct
